<?php
/**
 * @file
 * Main file, which implements main functionnalities for the capito authenticated module .
 *
 * @ingroup capito authenticated
 */
/**
 * Implements hook_init().
 */
function capito_authenticated_init() {
    global $user;
    if (!in_array("administrator", $user->roles) AND !in_array("webmaster", $user->roles)) {
        // Add JavaScript file.
        drupal_add_js(drupal_get_path('module', 'capito_authenticated') . '/js/hide-fields.js');
    }
}


